version: '2.1'

services:

  globodns_db:
    image: mysql:5.6
    container_name: globodnsdb.local 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: globodns
    networks:
      - mynetwork
    ports:
      - 3306:3306
    healthcheck:
      test: "(echo >/dev/tcp/localhost/3306) &>/dev/null"

  globodns:
    image: tuxmonteiro/globodns
    container_name: globodns
    depends_on:
      globodns_db:
        condition: service_healthy
    networks:
      - mynetwork
    ports:
      - 8080:8080
      - 53:53/udp

networks:
  mynetwork:

